### ISSUE TITLE
Infinite loop Issue with the sample wittyfiddle bot

### ISSUE THREAD

**Issue by tvvignesh** [wit-ai/witty-fiddle#41]
Tried the bot which was linked in the readme: https://wit-ai.github.io/witty-fiddle/?id=5a387f6ccb4be4a1f77f2113747a558a

Attaching the conversation which leads to this:

![test](https://cloud.githubusercontent.com/assets/1165845/21286929/f208a2a2-c486-11e6-8b87-74ada9ab7c7e.png)

**Comment by l5t** [comment]
Good catch, will fix on Monday cc @stopachka

**Comment by stopachka** [comment]
fixed! Thanks for reporting @tvvignesh 
![image](https://cloud.githubusercontent.com/assets/984574/21410621/eb9a4e76-c796-11e6-9233-d58228caab86.png)
