### ISSUE TITLE
FB undefined

### ISSUE THREAD

**Issue by znat** [wit-ai/witty-fiddle#42]
When I run the weather example I get the following error:

     WebApp.js:1231 Uncaught TypeError: Cannot read property 'AppEvents' of undefined(…)

The problematic line is WebApp.js:1231

    window.FB.AppEvents.logEvent('sentTextViaBrowser', 1);

where `FB` seems to be undefined.

Any idea?

**Comment by stopachka** [comment]
@znat -- it looks like we could have been loading without waiting for FB. Updated this diff to address this: 

https://github.com/wit-ai/witty-fiddle/commit/65a4e965ce7ab19f63ba756ed5ebfc9954614414

-- 

Please reopen if this doesn't fix it
