### ISSUE TITLE
Weatherbot Example shows only a pulsing dot

### ISSUE THREAD

**Issue by gfrivolt** [wit-ai/witty-fiddle#44]
Everything is loaded, but the app is not starting only the dot is pulsing in the middle of the page.

I visited that page  https://wit-ai.github.io/witty-fiddle/?id=5a387f6ccb4be4a1f77f2113747a558a from Chrome. No error in the console

**Comment by stopachka** [comment]
hey @gfrivolt , this is most likely because of the FB sdk not loading. 

Do you mind opening inspector, and sending me what you see in the resources pain? 

Something like this: 

![image](https://cloud.githubusercontent.com/assets/984574/21438197/abce1970-c83c-11e6-8cbc-3fac924b5eda.png)

**Comment by gfrivolt** [comment]
Hi @stopachka, here it is:

![wittyfiddle](https://cloud.githubusercontent.com/assets/98457/21440099/a513c972-c891-11e6-83f5-14fa20975d8b.jpg)

**Comment by stopachka** [comment]
Hey @gfrivolt -- do you have any chrome extensions running? Something that may block social media sites?

-- 

If you load this in an icognito window, can you tell me what happens?

**Comment by gfrivolt** [comment]
Yes, that was the issue. The Disconnect plugin blocked it. Bit strange such social media access, like this sdk.js, should not be blocked imo.

Thank you, and sorry for the confusion.

**Comment by stopachka** [comment]
No problem @gfrivolt!  Will report this incident to fb as well
